---
:concurrency: 3
:pidfile: tmp/pids/sidekiq.pid
staging:
  :concurrency: 10
production:
  :concurrency: 20

# queues中的队列出现的顺序,就是它们被worker处理的顺序
# A queue with a weight of 2 will be checked twice as often as a queue with a weight of 1:
:queues:
  # - [our_queue, 2] #第一个被处理 #weight 设置为2.注:最后不要混写
  - our_queue #第一个被处理 #weight 设置为2,
  - default #第二个被处理
  - low #第三个被处理
  - your_queue #最后一个被处理


# 处理队列顺序随机
# 注["foo", 1]带weight与不带weight的形式最好不要混写，
# 要么都带weight, 要么都不带，以便以指定的顺序让worker执行队列
# :queues:
#   - ["foo", 1]
#   - ["bar", 1]
#   - ["xyzzy", 1]

